services:
  api:
    build: .
    volumes:
      - .:/app
    image: user_content_api:latest
    command: bundle exec rails s -u puma -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:15.1
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test:
    build: .
    image: user_content_api:latest
    volumes:
      - .:/app
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rspec"
    depends_on:
      - db
    profiles: [ "test" ]
volumes:
  postgres_data:
